version: '3.8'
services:
  tftpd:
    container_name: "tftpd-pxe"
    build:
      context: .
      dockerfile: ./Dockerfile
      labels:
        - maintainer: jessenich
        - com.keplerdev.maintainer: Jesse N.
        - com.keplerdev.description: "Lightweight Alpine based TFTP server with PxE Boot Support."
    image: jessenich91/tftpd
    restart: unless-stopped
    environment:
      # Search the man page for --blocksize to learn more
      TFTPD_EXTRA_ARGS: '--blocksize 1468'
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - SYS_CHROOT
    ports:
      - 69:1069/udp
    volumes:
      - tftpd_boot:/tftpboot/boot
      - tftpd_configuration:/tftpboot/pxelinux.cfg:ro

volumes:
  tftpd_boot: {
    
  }
  tftpd_configuration: {
    
  }

