apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    maintainer: Jesse N. <jesse@keplerdev.com>
    org.opencontainers.image.source: https://github.com/jessenich/docker-tftpd-pxe
  name: tftpd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tftpd
    spec:
      restartPolicy: Always
      containers:
        - image: jessenich91/tftpd-pxe:latest
          name: tftpd-pxe
          ports:
            - containerPort: 1069
              hostPort: 69
              name: 1069udp69
              protocol: UDP
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities:
              add:
                - SETUID
                - SETGID
                - SYS_CHROOT
              drop:
                - ALL
          volumeMounts:
            - name: tftpd-boot
              mountPath: /tftp/boot/pxelinux.cfg

            - name: tftpd-configuration
              mountPath: tftpd-configuration
              readOnly: true


      volumes:
        - name: tftpd-boot
          persistentVolumeClaim:
            claimName: tftpd-boot
        - name: tftpd-configuration
          persistentVolumeClaim:
            claimName: tftpd-configuration
            readOnly: true
