---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: tftpd-configuration
  name: tftpd-configuration
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: tftpd-boot
  name: tftpd-boot
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
