name: Create Release


on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - v*

permissions:
  actions: read
  contents: read
  packages: write
  deployments: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Create Tag Release
        uses: Roang-zero1/github-create-release-action@v2.1.0
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          prerelease_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\-preview[[:digit:]]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
